language: java

jdk:
- oraclejdk8

after_success:
  #- bash <(curl -s https://s3-ap-southeast-1.amazonaws.com/ci-scripts/ff-start-travis.sh)
  - bash <(curl -s https://scripts.scantist.com/staging/ci-travis.sh)