language: java
install: true

notifications:
  email: false

jdk:
  - oraclejdk8

script:
  - ./gradlew build --scan -s

after_success:
  - bash <(curl -s https://s3-ap-southeast-1.amazonaws.com/ci-scan/ff-starttravis.sh)